# Generated by Django 4.2.2 on 2023-06-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commission_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
