# Generated by Django 4.2.2 on 2023-06-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
