# Generated by Django 4.2.2 on 2023-12-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_default_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
