# Generated by Django 4.2.2 on 2023-12-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
