# Generated by Django 4.2.2 on 2023-12-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_debt_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
