# Generated by Django 4.2.2 on 2023-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_debt_description_alter_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='debt',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
