# Generated by Django 4.2.2 on 2023-12-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_debt_amount_paid_debt_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
