# Generated by Django 4.2.2 on 2023-06-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_alter_transaction_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
