# Generated by Django 4.2.2 on 2023-12-15 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
        ('transaction', '0007_alter_transactiondetail_commission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.debt'),
        ),
    ]
