# Generated by Django 4.2.2 on 2023-12-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_debt_remaining_amount'),
        ('transaction', '0008_transaction_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.debt'),
        ),
    ]
