# Generated by Django 4.2.2 on 2023-12-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_transaction_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=8),
        ),
    ]
