# Generated by Django 4.2.2 on 2023-06-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
